dependencies:
# - <orginization/repo>@version>
- smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
    solc:
        remappings:
            - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
    sepolia:
        eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
wallets:
    from_key: ${PRIVATE_KEY}
        
            
